version: '3.7'

services:
  app:
    command: gunicorn --bind 0.0.0.0:5000 airq:app --reload
    env_file:
      - ./.env.dev
      - ./.env.dev.secrets
    expose:
      - "5000"
  nginx:
    build: 
      context: ./nginx
      args: [ "CONF_FILE=nginx.localhost.conf" ]
    ports:
      - 80:80
    depends_on:
      - app
  scheduler:
    env_file:
      - ./.env.dev
  worker:
    env_file:
      - ./.env.dev
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

volumes: 
  pgdata:
